name: Create APP and publish

on:
  push:
      branches: [ "main", "cicd" ]

#    tags:
#      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle.kts # or app/build.gradle.kts 
        versionCode: ${{github.run_number}}
        versionName: "0.0.1"
        #versionName: ${{ env.RELEASE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundleRelease
    - uses: Tlaster/android-sign@v1.2.2
      name: Sign app APK
      with:
        releaseDirectory: |
          app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        output: build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
    
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: karlosarr/pokedex
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Collaborators,Public
        file: app/build/outputs/bundle/signed/app-release.aab
        notifyTesters: true
        debug: false
    - uses: actions/upload-artifact@v3
      with:
        name: APP
        path: app/build/outputs/bundle/release/app-release.aab
